CREATE TABLE IF NOT EXISTS Livro (
  CodL INTEGER PRIMARY KEY AUTOINCREMENT CONSTRAINT Livro_PK,
  Titulo VARCHAR(40) NOT NULL,
  Editora VARCHAR(40) NOT NULL,
  Edicao INTEGER,
  AnoPublicacao VARCHAR(4) NOT NULL
);
