CREATE TABLE IF NOT EXISTS Livro_Autor (
  Livro_CodL INTEGER NOT NULL,
  Autor_CodAu INTEGER NOT NULL,
  CONSTRAINT Livro_Autor_FKIndex1 FOREIGN KEY (Livro_CodL) REFERENCES Livro (CodL) ON DELETE CASCADE,
  CONSTRAINT Livro_Autor_FKIndex2 FOREIGN KEY (Autor_CodAu) REFERENCES Autor (CodAu) ON DELETE CASCADE
);
