CREATE TABLE IF NOT EXISTS Livro (
  CodL INTEGER PRIMARY KEY AUTOINCREMENT CONSTRAINT Livro_PK,
  Titulo VARCHAR(40) NOT NULL,
  Editora VARCHAR(40) NOT NULL,
  Edicao INTEGER,
  AnoPublicacao VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS Autor (
  CodAu INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT CONSTRAINT Autor_PK,
  Nome VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Assunto (
  CodAs INTEGER PRIMARY KEY AUTOINCREMENT CONSTRAINT Assunto_PK,
  Descricao VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Livro_Autor (
  Livro_CodL INTEGER NOT NULL,
  Autor_CodAu INTEGER NOT NULL,
  CONSTRAINT Livro_Autor_FKIndex1 FOREIGN KEY (Livro_CodL) REFERENCES Livro (CodL),
  CONSTRAINT Livro_Autor_FKIndex2 FOREIGN KEY (Autor_CodAu) REFERENCES Autor (CodAu)
);

CREATE TABLE IF NOT EXISTS Livro_Assunto (
  Livro_CodL INTEGER NOT NULL,
  Assunto_CodAs INTEGER NOT NULL,
  CONSTRAINT Livro_Assunto_FKIndex1 FOREIGN KEY (Livro_CodL) REFERENCES Livro (CodL),
  CONSTRAINT Livro_Assunto_FKIndex2 FOREIGN KEY (Assunto_CodAs) REFERENCES Assunto (CodAs)
);
